---
title: "20210727 - Olympics"
author: "Nick Cruickshank"
date: "7/31/2021"
output: 
  github_document:
    toc: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
# libraries
library(ggtext)
library(ggstream)
library(patchwork)
library(readr)
library(readxl)
library(stringi)
library(tidyverse)
```

```{r data}
# data
olympics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv')

olympic_doping <- read_excel("olympic_doping.xlsx") %>%
  janitor::clean_names()
```

# Russian Blood Doping

[Wikipedia Page for Blood Doping Scandal](https://en.wikipedia.org/wiki/Doping_in_Russia)

```{r}
rus <- olympics %>%
  mutate(team = ifelse(team == "Soviet Union", "Russia", team)) %>%
  filter(
    season == "Summer",
    team == "Russia"
  ) %>%
  group_by(year, city) %>% #and by sport?
  dplyr::summarise(
    athletes = n_distinct(name),
    gold = sum(medal == "Gold", na.rm = TRUE),
    silver = sum(medal == "Silver", na.rm = TRUE),
    bronze = sum(medal == "Bronze", na.rm = TRUE),
    non_gold = sum(medal == "Silver" | medal == "Bronze", na.rm = TRUE)
  )

olympic_game_segments <- tibble(x = c(seq(1896, 1912, by = 4), seq(1920, 1936, by = 4), seq(1948, 2016, by = 4)), y = 3)

## retrieve olympic cities and years
summer_og_editions <- olympics %>%
  filter(season == "Summer") %>%
  distinct(year, city) %>%
  mutate(edition = glue::glue("{city}\n{year}")) %>%
  filter(
    !(year == 1906 & city == "Athina"),
    !(year == 1956 & city == "Stockholm")
  ) %>%
  arrange(year) %>%
  rowid_to_column() 
```

```{r Russian Medals by Blood Doping, fig.height=7, fig.width=18}
label_segment <- tibble(x = c(1948, 2002, 1994),
                        xend = c(1970, 2022, 2010),
                        y = c(72, 77, 50),
                        yend = c(72, 77, 50))

label_arrows <- tibble(x = c(1970, 2016, 2008),
                       xend = c(1978, 2016, 2008),
                       y = c(72, 77, 50),
                       yend = c(83, 43, 34))

medal_plot <- rus %>%
  pivot_longer(cols = c("gold", "silver", "bronze")) %>% #c("gold", "silver", "bronze") #c("gold", "non_gold")
  mutate(
    ratio = 100 * (value / athletes),
    #name = factor(name, levels = c("gold", "non_gold"))
    name = factor(str_to_title(name), levels = c("Gold", "Silver", "Bronze"))
  ) %>%
  ggplot() + 
  # dashed x grid
  geom_segment(data = olympic_game_segments, aes(x = x, xend = x, y = 0, yend = y), size = 0.5, color = "white", linetype = "dashed") +
  # details x axis labels
  geom_text(data = summer_og_editions, aes(x = year, y = -7, label = edition), 
            angle = 45, lineheight = 0.8, fontface = "bold", color = "white") +
  geom_col(aes(year, ratio, fill = name), color = "grey20") + 
  scale_fill_manual(values = c(
    "Gold" = "gold3",
    "Silver" = "gray60",
    "Bronze" = "darkgoldenrod4"
  )) + 
  # seqments for pointing out interesting bars
  geom_segment(data = label_segment, aes(x = x, xend = xend, y = y, yend = yend), color = "white") + 
  geom_segment(data = label_arrows, aes(x = x, xend = xend, y = y, yend = yend), color = "white", arrow = arrow(length = unit(2, "mm"))) +
  # title
  annotate("text", x = 1918, y = 80, label = "Percent of Russian\nAthletes to Medal", size = 10, fontface = "bold", color = "white") + 
  # subtitle
  # notes
  annotate(geom = "text", x = 1916, y = 10, label = "WORLD WAR I\n(1914-1918)", fontface = "bold", size = 5, color = "white") + 
  annotate(geom = "text", x = 1942, y = 10, label = "WORLD WAR II\n(1939-1945)", fontface = "bold", size = 5, color = "white") +
  annotate(geom = "text", x = 1958, y = 95, label = "The Chemists' Games", fontface = "bold", color = "white", size = 4.5) + 
  annotate(geom = "text", x = 1958, y = 83, label = "No athletes caught during the games.\nAdditional testing afterwards using new\ntechniques revealed 20% of specimens would\nhave resulted in disciplinary action.\nFirst documented case of blood doping.", color = "white") +
  annotate(geom = "text", x = 2012, y = 85, label = "38% of Russian atheletes submitted\nfor competition were rejected due\nto state-sponsored doping scandal", color = "white", size = 4.5) +
  annotate(geom = "text", x = 2002, y = 60, label = "As of 2017,\nthe 2008 Olympics has had\nthe most (50) medals stripped.\nRussia leads with 14 medals.", color = "white", size = 4.5) +
  coord_cartesian(xlim = c(1896, 2024), ylim = c(-10, 100)) +
  scale_x_continuous(name = NULL) +
  scale_y_continuous(name = NULL, labels = function(x) paste0(x, "%")) +
  theme(
    plot.background = element_rect(fill = "gray20"),
    panel.background = element_rect(fill = "gray20"),
    panel.grid = element_blank(),
    legend.position = "none",
    axis.text.y = element_text(color = "white", size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.caption = element_markdown(color = "white", size = 12)
  )
```

```{r tidy olympic_doping}
# tidy olympic doping
dope <- olympic_doping %>%
  fill(c(name, country), .direction = "down") %>%
  filter(str_detect(country, "(Russia|Soviet Union)")) %>%
  mutate(
    medal = case_when(
      str_detect(medals, "gold") ~ "Gold",
      str_detect(medals, "silver") ~ "Silver",
      str_detect(medals, "bronze") ~ "Bronze"
    )
  ) %>%
  select(year, city, anti_doping_rule_violation, sport, dns, medal)
```

```{r}
# bar chart of russian dopers at each games
## y axis in percent of total atheletes
## fill with sport
## inverted bar chart to be placed below the primary plot

rus_ath_year <- olympics %>%
  filter(
    season == "Summer", 
    str_detect(team, "(Russia|Soviet Union)")
  ) %>%
  group_by(year) %>% # and by sport if possible
  dplyr::summarise(
    athletes = n_distinct(name)
  )

dope_plot <- dope %>%
  count(year, city) %>% # and by sport if possible 
  inner_join(rus_ath_year) %>%
  mutate(prop = 100 * (n / athletes)) %>%
  ggplot(aes(year, -prop)) + 
  geom_bar(stat = "identity", fill = "firebrick1") + 
  geom_text(aes(label = paste0(round(prop, 1), "%")), color = "white", fontface = "bold", vjust = 1) +
  # title
  annotate(geom = "text", x = 1992, y = -10, label = "Percent of Russian\natheltes caught doping", color = "white", fontface = "bold", size = 6) +
  # subtitle
  annotate(geom = "text", x = 1992, y = -20, label = "(not all athletes who were caught doping\nwon a medal)", fontface = "italic", color = "white", size = 4) +
  scale_y_continuous(name = NULL, labels = function(x) paste0(abs(x), "%")) + 
  coord_cartesian(xlim = c(1976, 2028), ylim = c(-30, 0)) +
  scale_x_continuous(name = NULL) +
  theme(
    plot.background = element_rect(fill = "gray20"),
    panel.background = element_rect(fill = "gray20"),
    panel.grid = element_blank(),
    axis.text.y = element_blank(), #element_text(color = "white", size = 15),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
  )
```

```{r}
# pie chart of which drugs used by dopers
## will likely need to tidy 'anti_doping_rule_violation' column and separate_rows()
rus_drugs <- dope %>%
  filter(!(is.na(anti_doping_rule_violation))) %>%
  mutate(
    anti_doping_rule_violation = str_remove(anti_doping_rule_violation, "\\s*\\([^\\)]+\\)")
  ) %>%
  separate_rows(anti_doping_rule_violation, sep = "(,|&|\\sor |\\sand)") %>%
  mutate(anti_doping_rule_violation = str_trim(anti_doping_rule_violation))
  
# get the most common drugs
top_drugs <- rus_drugs %>%
  count(anti_doping_rule_violation, sort = TRUE) %>%
  head(3) %>%
  pull(anti_doping_rule_violation)

rus_drugs2 <- rus_drugs %>%
  mutate(
    drug = fct_other(anti_doping_rule_violation, keep = top_drugs, other_level = "Other"),
    drug = str_to_title(drug)
  ) %>%
  count(drug, sort = TRUE)

drug_pie_plot <- rus_drugs2 %>%
  arrange(desc(drug)) %>%
  mutate(
    prop = n / sum(rus_drugs2$n) * 100,
    ypos = cumsum(prop) - 0.5 * prop
  ) %>%
  ggplot(aes(x = "", y = prop, fill = drug)) + 
  geom_bar(stat = "identity", width = 1, color = "white") + 
  geom_text(aes(y = ypos, label = paste0(round(prop), "%")), color = "white", size = 4) +
  #scale_fill_brewer(palette = "Reds") + 
  scale_fill_manual(values = c("lightpink2", "grey80", "red2", "darkred")) +
  coord_polar("y", start = 0) + 
  labs(
    fill = "Distribution of\nBanned Substances",
    x = "",
    y = ""
  ) +
  theme(
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    plot.background = element_rect(fill = "gray20"),
    panel.background = element_rect(fill = "gray20"),
    legend.text = element_text(color = "white", size = 12),
    legend.title = element_text(color = "white", face = "bold", size = 14),
    legend.background = element_blank()
  )
```

```{r}
# pie chart of which sports had the most dopers
sports <- dope %>%
  mutate(
    category = case_when(
      str_detect(sport, "[0-9]\\skg") ~ "Weightlifting",
      str_detect(str_to_lower(sport), "(metre(s)?|relay|walk|marathon|throw|jump|shot put|pole vault|track)") ~ "Track and Field",
      TRUE ~ sport
    )
  ) %>%
  count(category, sort = TRUE)

top_sports <- pull(head(sports, 3), category)

sport_pie <- sports %>%
  mutate(
    sport = fct_other(category, keep = top_sports, other_level = "Other")
  ) %>%
  group_by(sport) %>%
  dplyr::summarise(n = sum(n))

sport_pie2 <- sport_pie %>%
  arrange(desc(sport)) %>%
  mutate(
    prop = n / sum(sport_pie$n) * 100,
    ypos = cumsum(prop) - 0.5 * prop
  )

sport_pie_plot <- sport_pie2 %>%
  ggplot(aes(x = "", y = prop, fill = sport)) + 
  geom_bar(stat = "identity", width = 1, color = "white") + 
  geom_text(aes(y = ypos, label = paste0(round(prop), "%")), color = "white", size = 4) +
  #scale_fill_brewer(palette = "Reds") + 
  scale_fill_manual(values = c("darkred", "red2", "lightpink2", "gray80")) +
  coord_polar("y", start = 0) + 
  labs(
    fill = "Distribution of Blood\nDoping Athletes by Sport",
    x = "",
    y = ""
  ) +
  theme(
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    plot.background = element_rect(fill = "gray20"),
    panel.background = element_rect(fill = "gray20"),
    legend.text = element_text(color = "white", size = 12),
    legend.title = element_text(color = "white", face = "bold", size = 14),
    legend.background = element_blank()
  )
```

```{r History of Russian Olympic Doping, fig.height=10, fig.width=18}
caption <- "**Source:** sports-reference.com & Kaggle  |  **More Info:** en.wikipedia.org/wiki/Doping_at_the_Olympic_Games  |  **Visualization By:** Nick Cruickshank"

medal_plot /
  (drug_pie_plot + sport_pie_plot + dope_plot) +
  plot_layout(heights = c(10,3)) + 
  plot_annotation(
    title = "Relationship between Russian Olympic Performance and Blood Doping",
    caption = caption,
    theme = theme(
      plot.background = element_rect(fill = "gray20", color = "gray20"),
      plot.title = element_text(size = 32, color = "white", face = "bold"),
      plot.caption = element_textbox(size = 12, color = "white"),
    )
  )
```
