---
title: "20210817 - Star Trek Commands"
author: "Nick Cruickshank"
date: "8/19/2021"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
# libraries
library(ggtext)
library(readr)
library(sentimentr)
library(tidytext)
library(tidyverse)
```

```{r data}
# data
computer <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-17/computer.csv')
```

# NCruickshank Tweet

```{r}
computer
```

## Who had the most interactions with the computer?

```{r}
computer %>%
  filter(!(str_detect(char, "(Computer|Com Panel)"))) %>%
  count(char, sort = TRUE) %>%
  head(10)
```

## Sentiment Analysis by Star Trek Character and Interaction Type

What was the average sentiment value for these metrics?

```{r Star Trek Sentiment by Character and Command Type, fig.height=3.5, fig.width=8}
char_sent <- computer %>%
  # I care about human to computer interactions here
  filter(!(str_detect(char, "(Computer|Com Panel)"))) %>%
  select(char, pri_type, line) %>%
  mutate(observation = row_number()) %>%
  get_sentences() %$%
  sentiment_by(line, by = list(char, pri_type, observation)) %>%
  unite("char_pri", char:pri_type, remove = FALSE)

top_characters <- head(count(char_sent, char, sort = TRUE), 5)$char

char_sent2 <- char_sent %>%
  filter(char %in% top_characters) %>%
  group_by(char, pri_type) %>%
  summarise(
    observations = n(),
    avg_word_count = mean(word_count),
    avg_line_sentiment = mean(ave_sentiment)
  ) %>%
  ungroup() %>%
  mutate(
    sign = ifelse(avg_line_sentiment < 0, "Negative", "Positive"),
    abs_sentiment = abs(avg_line_sentiment),
    char = factor(char, levels = top_characters)
  )

char_sent2 %>%
  ggplot(aes(char, pri_type)) + 
  geom_point(aes(size = abs_sentiment, color = sign)) + 
  scale_color_manual(values = c("Red", "Green")) + 
  guides(size = "none", color = "none") +
  labs(
    title = "Sentiment Analysis of Star Trek Characters by Interaction Type",
    subtitle = "Size represents absolute sentiment while color represents direction (<b style='color:red'>negative</b> or <b style='color:green'>positive</b>)",
    x = "Character",
    y = "Interaction Type"
  ) + 
  theme_minimal() + 
  theme(
    plot.subtitle = element_textbox()
  )
```

### Facetted boxplots for each character by interaction type

# Other Tweets

```{r neuroandstats plot}
# @neuroandstats Analysis
## https://twitter.com/neuroandstats/status/1427733648086814725
summarized_computer <- computer %>%
  summarise(char_type, line, pri_type)

summarized_computer$observation <- 1:nrow(summarized_computer)

avg_sentiment <- summarized_computer %>%
  get_sentences() %$% # weird that we're not piping here, but ok
  sentiment_by(line, by = list(char_type, pri_type, observation)) %>%
  unite("char_pri", char_type:pri_type, remove = FALSE)

neuroandstats_plot <- avg_sentiment %>%
  ggplot(aes(ave_sentiment, reorder(char_pri, ave_sentiment))) + 
  geom_jitter(alpha = 0.3, color = "black") + 
  geom_point() + 
  stat_summary(fun = "mean", geom = "point", size = 3, shape = 24, fill = "red") + 
  labs(
    title = "Sentiment analysis of Star Trek speech interactions",
    x = "Average Sentiment Value",
    y = "Type of Dialog",
    caption = "Tidy Tuesday week 34 \ndata courtesy of SpeechInteraction.org"
  )
```


